services:
  pydockmate:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./pydockmate-data:/var/www/PyDockMate/pydockmate-data
  pydockmate-consumer:
    build:
      dockerfile: ./Dockerfile.consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: password 
    volumes:
      - ./pydockmate-data:/var/www/PyDockMate/pydockmate-data
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5552:5552"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_log:/var/log/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
