FROM python:3.14-slim

ENV PIP_ROOT_USER_ACTION=ignore
WORKDIR /var/www/PyDockMate
COPY . .
RUN mkdir -p /var/www/PyDockMate/pydockmate-data

RUN apt-get update
RUN apt-get install socat -y
RUN pip install -r requirements.txt  

CMD ["/bin/sh", "-c", "socat TCP-LISTEN:5552,reuseaddr,fork TCP:rabbitmq:5552 & python -u manage.py rabbit_mq_consumer"]
