# Generated by Django 6.0.2 on 2026-02-17 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid7, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('docker_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid7, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=12)),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PyDockMate.host')),
            ],
        ),
    ]
