# Generated by Django 6.0.2 on 2026-02-19 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid7, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=64)),
                ('image', models.CharField()),
                ('command', models.CharField()),
                ('created', models.DateTimeField()),
                ('ports', models.CharField()),
                ('name', models.CharField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyDockMate.host')),
            ],
        ),
    ]
