# Generated by Django 6.0.2 on 2026-02-25 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0002_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
                ('timestamp', models.DateTimeField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyDockMate.container')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['container', 'timestamp'], name='container_timestamp_index')],
                'constraints': [models.UniqueConstraint(fields=('container', 'timestamp'), name='unique_container_timestamp')],
            },
        ),
    ]
