# Generated by Django 6.0.2 on 2026-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0003_containerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstat',
            name='cpu',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
