# Generated by Django 6.0.2 on 2026-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0004_containerstat_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstat',
            name='memory',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
