# Generated by Django 6.0.2 on 2026-03-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0005_containerstat_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerstat',
            name='cpu',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='containerstat',
            name='memory',
            field=models.FloatField(null=True),
        ),
    ]
