# Generated by Django 6.0.2 on 2026-03-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0006_alter_containerstat_cpu_alter_containerstat_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstat',
            name='network_rx_bytes',
            field=models.IntegerField(null=True),
        ),
    ]
