# Generated by Django 6.0.2 on 2026-03-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyDockMate', '0007_containerstat_network_rx_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstat',
            name='network_tx_bytes',
            field=models.IntegerField(null=True),
        ),
    ]
